### PR TITLE
Added a Comment Section Project using PHP

### PR DESCRIPTION
**Pull request by AryanSahoo-2003**
Showed how to make a basic Comment section box using php on your local machine taking input in a seperate comment.txt file
image

### CODE REVIEW

**Comment by AryanSahoo-2003** [comment]
hello sir,why is my repo not showing on hactoberfest 2022 and it is showing excluded?

**Comment by ishaangupta-YB** [comment]
> hello sir,why is my repo not showing on hactoberfest 2022 and it is showing excluded?

Iam in contact with the team regarding this, it might be included soon. Till then you can contribute to other projects.

**Comment by AryanSahoo-2003** [comment]
Sir..now what is the result?

**Comment by AryanSahoo-2003** [comment]
Sir could you please tell me if it would be included or not?

**Comment by AryanSahoo-2003** [comment]
Hello sir!!Could you reply please :?

**Comment by ishaangupta-YB** [comment]
> Sir could you please tell me if it would be included or not?

Hey @AryanSahoo-2003 
Kindly contribute in other repos which are included. It doesn't seems like this one gonna be included for now.
Thank You

**Comment by AryanSahoo-2003** [comment]
Ok sir ...I will just do that!! Thank you for replying:)

**Pull request merged**
